# Change these first
owner: LakesideNetwork # Your GitHub username
repo: website-uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: LakesideLink
    url: https://lakesidelink.com
  - name: Lakeside Training
    url: https://lakesidetraining.org
  - name: Lakeside Garage
    url: https://lakesidegarage.shop
  - name: Lakeside Greenhouse
    url: https://lakesidegreenhouse.org
  - name: Lakeside Global
    url: https://lakesideglobal.org
  - name: Lakeside Technology
    url: https://lakesidetechnology.org

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /website-uptime
  logoUrl: https://lakesidelink.com/wp-content/uploads/2018/05/cropped-Lakeside_logo.png
  name: Lakeside Websites Status Page
  introTitle: 
  introMessage: Website monitoring for all Lakeside domains.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
